# Generated by Django 3.0.2 on 2021-10-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('qtd', models.PositiveIntegerField()),
                ('unid', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['desc', 'marca', 'qtd'],
            },
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome de um mercado', max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Em_Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('pd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ofertas.Produto')),
                ('sm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ofertas.Supermercado')),
            ],
            options={
                'verbose_name': 'Em oferta',
                'verbose_name_plural': 'Em oferta',
                'ordering': ['pd', 'preco'],
            },
        ),
    ]
