# Generated by Django 3.0.2 on 2021-10-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
